
project_id = "pdjgzhajrdhksvugdkuf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://pdjgzhajrdhksvugdkuf.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_anonymous_users = false
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false

[edge_functions]
enabled = true

[[edge_functions.functions]]
name = "evolution-api"
verify_jwt = true

[[edge_functions.functions]]
name = "evolution-webhook"
verify_jwt = false
