// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdjgzhajrdhksvugdkuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkamd6aGFqcmRoa3N2dWdka3VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTAzMDIsImV4cCI6MjA2MzkyNjMwMn0.PSJwA7zK9I653ww0qtJ7Pdzt0y_9OUjOJzOGDUEVsJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);